export const url = {
  specialityUrl: '/speciality',
  studentUrl: '/Student',
  subjectUrl: '/Subject',
  facultyUrl: '/Faculty',
  timeTableUrl: '/TimeTable',
  groupUrl: '/Group',
  testUrl: '/Test',
  testDetailUrl: '/TestDetail',
  questionUrl: '/question',
  answerUrl: '/answer',
  resultUrl: '/result',
  getCount: '/countRecords',
  getRecordsRange: '/getRecordsRange',
  getRecords: '/getRecords',
  insertData: '/insertData',
  update: '/update',
  delete: '/del',
  getRecordsBySearch: '/getRecordsBySearch',
  getTestsBySubject: '/getTestsBySubject',
  getTestDetailsByTest: '/getTestDetailsByTest',
  getAnswersByQuestion: '/getAnswersByQuestion',
  getStudentsByGroup: '/getStudentsByGroup',
  getQuestionIdsByLevelRand: '/getQuestionIdsByLevelRand',
  getRecordsRangeByTest: '/getRecordsRangeByTest',
  countRecordsByTest: '/countRecordsByTest',
  getEntityValues: '/getEntityValues',
  checkUserName: '/checkUserName',
  checkEmailAddress: '/checkEmailAddress',
  adminUser: '/AdminUser'

};
