export const urlConstants = {
  specialityUrl: '/speciality',
  studentUrl: '/Student',
  subjectUrl: '/Subject',
  facultyUrl: '/Faculty',
  timeTableUrl: '/TimeTable',
  groupUrl: '/Group',
  testUrl: '/Test',
  testDetailUrl: '/TestDetail',
  getCount: '/countRecords',
  getRecordsRange: '/getRecordsRange',
  getRecords: '/getRecords',
  insertData: '/insertData',
  getTestsBySubject: '/getTestsBySubject',
  getTestDetailsByTest: '/getTestDetailsByTest',
  question: '/question',
  getQuestionIdsByLevelRand: 'getQuestionIdsByLevelRand',
  getAnswersByQuestionTestPlayerUrl: 'SAnswer/getAnswersByQuestion',
  checkSAnswerUrl: 'SAnswer/checkAnswers'
};
